### ISSUE TITLE
text object `a<` or `i<` doesn't work!

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#123]
<a href="https://github.com/babygau"><img src="https://avatars1.githubusercontent.com/u/1514823?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [babygau](https://github.com/babygau)**
_Thursday Mar 19, 2015 at 12:31 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/877_

----

when i want to change content inside a block of `<>`, `a<` or `i<` don't work. but `a>` or `i>` work for me.

here is the console output:

``` log
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "xactions in C:\Users\brade_000\AppData\Roaming\Sublime Text 3\Installed Packages\Vintageous.sublime-package", line 778, in run
  File "state in C:\Users\brade_000\AppData\Roaming\Sublime Text 3\Installed Packages\Vintageous.sublime-package", line 692, in process_user_input2
  File "vi.cmd_defs in C:\Users\brade_000\AppData\Roaming\Sublime Text 3\Installed Packages\Vintageous.sublime-package", line 3364, in accept
AssertionError: `i` only accepts a single char
```

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Thursday Apr 23, 2015 at 19:44 GMT_

----

i cannot process '<' as it mixes it up with '<lt>'.
