### ISSUE TITLE
`Vitageous` crashed after running `Ruby Beautify` or `Pretty Ruby`

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#140]
<a href="https://github.com/babygau"><img src="https://avatars1.githubusercontent.com/u/1514823?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [babygau](https://github.com/babygau)**
_Wednesday May 27, 2015 at 13:47 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/966_

----

I run into this issue whenever I execute `Ruby Beautify` or `Pretty Ruby` from Sublime Text Command

Here is the bug, hope it helps

``` python
Traceback (most recent call last):
  File "state in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 652, in update_xpos
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "xactions in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 355, in run
  File "state in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 655, in update_xpos
AttributeError: 'function' object has no attribute 'error'
unsupported operand type(s) for *: 'int' and 'NoneType'
Traceback (most recent call last):
  File "state in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 652, in update_xpos
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "xactions in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 355, in run
  File "state in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 655, in update_xpos
AttributeError: 'function' object has no attribute 'error'
```

**Comment by gerardroche** [comment]
@babygau This has been fixed in a recent version (NeoVintageous is a fork of the discontinued Vintageous plugin).
