### ISSUE TITLE
 j k h l doesn't work

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#143]
<a href="https://github.com/l1nxy"><img src="https://avatars3.githubusercontent.com/u/12152770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [l1nxy](https://github.com/l1nxy)**
_Friday May 22, 2015 at 07:04 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/960_

----

> Traceback (most recent call last):
>   File "vi.utils in E:\Program Files\Sublime Text 3\Data\Installed Packages\Vintageous.sublime-package", line 286, in run_
> AttributeError: '_vi_j' object has no attribute 'filter_args'
> Traceback (most recent call last):
>   File "vi.utils in E:\Program Files\Sublime Text 3\Data\Installed Packages\Vintageous.sublime-package", line 286, in run_
> AttributeError: '_vi_h' object has no attribute 'filter_args'
> Traceback (most recent call last):
>   File "vi.utils in E:\Program Files\Sublime Text 3\Data\Installed Packages\Vintageous.sublime-package", line 286, in run_
> AttributeError: '_vi_k' object has no attribute 'filter_args'
> Traceback (most recent call last):
>   File "vi.utils in E:\Program Files\Sublime Text 3\Data\Installed Packages\Vintageous.sublime-package", line 286, in run_
> AttributeError: '_vi_l' object has no attribute 'filter_args'

**Comment by gerardroche** [comment]
<a href="https://github.com/l1nxy"><img src="https://avatars3.githubusercontent.com/u/12152770?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [l1nxy](https://github.com/l1nxy)**
_Friday May 22, 2015 at 07:09 GMT_

----

https://github.com/guillermooo/Vintageous/issues/923
