### ISSUE TITLE
cursor get stucked after a few edit operations

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#153]
<a href="https://github.com/tom-kuca"><img src="https://avatars0.githubusercontent.com/u/171436?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tom-kuca](https://github.com/tom-kuca)**
_Sunday May 03, 2015 at 11:36 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/950_

----

At particular ruby file, Vintageous crashes after couple of operations. After the crash, the cursor is stucked - I can't move it using hjkl or other motions. If I try to, the current line blinks and the cursor doesn't move. After Reset, it works. 

I wasn't able to find the exact operations which cause it, but it happens usually within a minute. An example of a 'bad' operation is to copy (`yyp`) the last line `end`. The description is probably not too helpful, so I tried to look into the source. I have found two issues - an exception occured, and a bug in the exception handler (missing `()`).

The bug in the exception handler should be fixed by #949. After the patch, it works - the cursor is not stucked anymore. The exception is still there, but I can see it only in the error console.

The exception is raised because of undefined value of `tab_size` at [state.py](https://github.com/guillermooo/Vintageous/blob/1c1b29cda769b70168dbd72f9597534da003f247/state.py#L650)

``` python
self.view.settings().get('tab_size') # None
```

The 'Indent Using Spaces` is not checked and the status bar says that the Tab size is 4.

Backtrace:

```
unsupported operand type(s) for *: 'int' and 'NoneType'
[2015-05-03 12:33:00,328 - ERROR    - Vintageous.state] Vintageous: Error when setting xpos. Defaulting to 0.
Traceback (most recent call last):
File "/opt/sublime_text_3/sublime_plugin.py", line 533, in run_
    return self.run(**args)
File "/home/tomas/.config/sublime-text-3/Packages/Vintageous/xactions.py", line 885, in run
    state.reset_command_data()
File "/home/tomas/.config/sublime-text-3/Packages/Vintageous/state.py", line 611, in reset_command_data
    self.update_xpos()
File "/home/tomas/.config/sublime-text-3/Packages/Vintageous/state.py", line 661, in update_xpos
    raise e
File "/home/tomas/.config/sublime-text-3/Packages/Vintageous/state.py", line 655, in update_xpos
    ((counter['\t'] * tab_size) - counter['\t']))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

Sublime Text 3 Build 3083.

**Comment by gerardroche** [comment]
The exception handling is fixed. If the `tab_size` setting returns `None` an exception will be raised. `tab_size` should never really `None`. If it is intentionally set `None` for some reason then the exception in this case can be ignored. I think maybe reqrite it so that: if `tab_size` doesn't return an integer greater 0 then we'll just set the xpos to 0, instead of raising an exception.
