### ISSUE TITLE
After updates, I can't get into command mode

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#155]
<a href="https://github.com/jbailey"><img src="https://avatars3.githubusercontent.com/u/15834?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jbailey](https://github.com/jbailey)**
_Monday Apr 27, 2015 at 16:54 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/943_

----

The first time this happened I somehow managed to get back into command mode and then it started working like normal.  I'm not sure how I did it, I think I may have been through reset.  This time I've been unable to get into command mode.

Any ideas?

**Comment by gerardroche** [comment]
<a href="https://github.com/jbailey"><img src="https://avatars3.githubusercontent.com/u/15834?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jbailey](https://github.com/jbailey)**
_Tuesday Apr 28, 2015 at 17:58 GMT_

----

This is on mac.  I don't really have any more details.  After being updated, I can't get into command mode at all.

**Comment by gerardroche** [comment]
<a href="https://github.com/mswiatlo"><img src="https://avatars3.githubusercontent.com/u/3971806?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mswiatlo](https://github.com/mswiatlo)**
_Tuesday Apr 28, 2015 at 18:41 GMT_

----

Similarly having issues. OS X 10.10.3, Sublime Text Stable Channel Build 3083. Using Package Control to install the Vintageous, so it auto-updated recently and stopped working (i.e., pressing Escape doesn't send me to command mode). I'm sorry that I can't remember if it was the 4.0 build, or a later one which broke this.

I've tried disabling Vintageous and re-enabling with Package Control, but no dice. Restarting Sublime likewise doesn't help. Happy to provide more specific answers/data if you have questions!

**Comment by gerardroche** [comment]
<a href="https://github.com/mattrrichard"><img src="https://avatars0.githubusercontent.com/u/3155381?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattrrichard](https://github.com/mattrrichard)**
_Wednesday Apr 29, 2015 at 15:15 GMT_

----

I'm also having this issue on both OS X (10.10.2) and Windows 7, both running Vintageous from Package Control and ST build 3083.

**Comment by gerardroche** [comment]
<a href="https://github.com/krohrbaugh"><img src="https://avatars0.githubusercontent.com/u/40621?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [krohrbaugh](https://github.com/krohrbaugh)**
_Monday May 04, 2015 at 21:36 GMT_

----

Also seeing this. The ST console is outputting the following many times on boot and the plugin is effectively disabled.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "xactions in /Users/krohrbaugh/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 290, in run
  File "vi.core in /Users/krohrbaugh/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 49, in state
  File "state in /Users/krohrbaugh/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 177, in __init__
TypeError: 'NoneType' object is not callable
```

As for repro steps, the plugin updated (to v4.0.3) on restart via package control and then began failing. I'm running ST3, Stable Build 3083 on MacOS X 10.10.3.

---

_Update:_ I uninstalled the package (via Package Control) and reinstalled (still v4.0.3) and everything is working again. O_o

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday May 04, 2015 at 21:41 GMT_

----

Are you using other plugins? Have you tried disabling every plugin except Vintageous?

**Comment by gerardroche** [comment]
<a href="https://github.com/mswiatlo"><img src="https://avatars3.githubusercontent.com/u/3971806?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mswiatlo](https://github.com/mswiatlo)**
_Monday May 04, 2015 at 21:46 GMT_

----

Following @krohrbaugh's tip, I re-installed (remove package and install package via Package Control) and it also is working right away.  Thanks very much! Might be good to put this tip in the README, if it's not clear what the real issue is.

For the record, I use a number of other packages:

ColorSublime
Git
GitGutter
LatexTools
Package Control
Theme - Soda

**Comment by gerardroche** [comment]
<a href="https://github.com/kuna-matata"><img src="https://avatars2.githubusercontent.com/u/7603182?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kuna-matata](https://github.com/kuna-matata)**
_Wednesday May 13, 2015 at 13:57 GMT_

----

Another broken update. I'm running on windows 7. I updated sublime text 3 to build 3083. Vintageous completely stopped working. I downloaded the latest prebuilt version from the vintageous github page, and saved into the sublime packages folder. Now command mode and edit mode work, but ':' commands do not work. Help!!! My life depends on vintageous.

**Comment by gerardroche** [comment]
<a href="https://github.com/kuna-matata"><img src="https://avatars2.githubusercontent.com/u/7603182?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kuna-matata](https://github.com/kuna-matata)**
_Wednesday May 13, 2015 at 19:18 GMT_

----

Got it working. Installed package control. Then used package control to install vintageous. Worked like a charm, plus learned about package control. very cool.

**Comment by gerardroche** [comment]
<a href="https://github.com/alank64"><img src="https://avatars3.githubusercontent.com/u/1436615?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alank64](https://github.com/alank64)**
_Wednesday Feb 10, 2016 at 06:16 GMT_

----

Not sure if this will help...

Sublime Build 3103
Vintageous 4.0.4
OSX 10.11.1

After almost more than an hour of trying to get the escape key to work with this sexy Vintageous (first time I hear about it and wanted to try, mostly a Vintage user until now), the only way I could finally get the `<esc>` key (back to command mode) to work was finally discovering that the `Default (OSX).sublime-keymap` still had some Vintage mode settings, while none of the many Vintageous settings, so I cut/paste the whole thing into it, _et voila!_ Escape is working nicely!!!

See this repository file and cut all the text:

https://github.com/guillermooo/Vintageous/blob/master/Default.sublime-keymap

And do your `<shift><cmd> P` - enter "keymap" and select `Default (OSX).sublime-keymap`

paste it all right here, but warning, I'm not sure what other plugings' settings so careful, I only had my old Vintage plugin settings, so wiped them right out.

For Linux or Windows, sorry, can't vouch for this solution, but maybe it might help to verify those settings.

-- Vintageous IS AMAZING - SO FAST!!! I'm now a fan -- Sorry first time I heard or tried it, despite the escape key issue, I'm already in love!!!

**Comment by gerardroche** [comment]
I'm closing this. If this is still an issue please open a fresh issue specific to NeoVintageous. Please provide a startup log i.e. go to menu > show console. Also enable command and input logging i.e. in the input box at the bottom of the console run: `sublime.log_commands(True); sublime.log_input(True)`
