### ISSUE TITLE
Wiki: ToggleVintageous 

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#203]
<a href="https://github.com/sursir"><img src="https://avatars0.githubusercontent.com/u/8121715?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sursir](https://github.com/sursir)**
_Monday Dec 07, 2015 at 09:21 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1050_

----

```
Traceback (most recent call last):
  File "F:\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "xactions in F:\Sublime Text 3\Data\Installed Packages\Vintageous.sublime-package", line 304, in run
  File "vi.core in F:\Sublime Text 3\Data\Installed Packages\Vintageous.sublime-package", line 49, in state
  File "state in F:\Sublime Text 3\Data\Installed Packages\Vintageous.sublime-package", line 180, in __init__
TypeError: 'NoneType' object is not callable
```

It's broken when reset Vintageous after that toggle vintageous

**Comment by gerardroche** [comment]
Relates to https://github.com/NeoVintageous/NeoVintageous/issues/246
