### ISSUE TITLE
`>>` results in a traceback

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#225]
<a href="https://github.com/babygau"><img src="https://avatars1.githubusercontent.com/u/1514823?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [babygau](https://github.com/babygau)**
_Wednesday Oct 14, 2015 at 12:14 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1016_

----

Hi @guillermooo,

I got this traceback while using vim indent with `>>`:

``` bash
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "xactions in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 1702, in run
  File "vi.utils in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 151, in regions_transformer
  File "xactions in /Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 1689, in f
AttributeError: 'module' object has no attribute 'get'
```

**Comment by gerardroche** [comment]
<a href="https://github.com/babygau"><img src="https://avatars1.githubusercontent.com/u/1514823?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [babygau](https://github.com/babygau)**
_Thursday Oct 15, 2015 at 01:08 GMT_

----

I think the issue would be related to this #1009

**Comment by gerardroche** [comment]
@babygau It looks like this has since been fixed in NeoVintageous (NeoVintageous is a fork of the discontinued Vintageous plugin). Please let me know if it's still issue for you and I'll repopen.
