### ISSUE TITLE
Error when toggling vintageous

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#246]
<a href="https://github.com/mhahn"><img src="https://avatars0.githubusercontent.com/u/704593?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mhahn](https://github.com/mhahn)**
_Thursday Jun 18, 2015 at 22:36 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/974_

----

I get the following error when trying to toggle vintageous:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "xactions in /Users/mhahn/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 290, in run
  File "vi.core in /Users/mhahn/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 49, in state
  File "state in /Users/mhahn/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 177, in __init__
TypeError: 'NoneType' object is not callable
```

I set up toggling via: https://github.com/guillermooo/Vintageous/wiki/Toggling-Vintageous

**Comment by gerardroche** [comment]
<a href="https://github.com/louwers"><img src="https://avatars1.githubusercontent.com/u/649392?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [louwers](https://github.com/louwers)**
_Monday Oct 26, 2015 at 15:13 GMT_

----

I get the following when enabling Vintageous:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "xactions in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 304, in run
  File "vi.core in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 49, in state
  File "state in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous.sublime-package", line 180, in __init__
TypeError: 'NoneType' object is not callable
```

After restarting Sublime, Vintageous works again.
