### ISSUE TITLE
aW text objects error if cursor starts at whitespace

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#281]
The following raises an exception:

```
Traceback (most recent call last):
  File "/path/to/Packages/NeoVintageous/lib/vi/utils.py", line 306, in run_
    return self.run(**args)
  File "/path/to/Packages/NeoVintageous/lib/cmds/vi_motions.py", line 2017, in run
    regions_transformer(self.view, f)
  File "/path/to/Packages/NeoVintageous/lib/vi/utils.py", line 170, in regions_transformer
    region = f(view, sel)
  File "/path/to/Packages/NeoVintageous/lib/cmds/vi_motions.py", line 2006, in f
    count=count)
  File "/path/to/Packages/NeoVintageous/lib/vi/text_objects.py", line 345, in get_text_object_region
    if not w:
  File "/home/code/sublime_text_3/sublime.py", line 564, in __len__
    return self.size()
  File "/home/code/sublime_text_3/sublime.py", line 594, in size
    return abs(self.a - self.b)
TypeError: unsupported operand type(s) for -: 'Region' and 'int'
```

Example

```
a   |     b
```

Command: `daW` or `caW` where cursor is `|`.

**Comment by gerardroche** [comment]
Relates to #123 and #280
