### ISSUE TITLE
% should jump to the next item in this line after the cursor

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#352]
Pressing `%` at:

```
<?php

|function x() {
    // ...
}

```

causes an exception:

```
Traceback (most recent call last):
  File "/home/code/.config/sublime-text-3/Packages/NeoVintageous/nv/vi/utils.py", line 216, in run_
    return self.run(**args)
  File "/home/code/.config/sublime-text-3/Packages/NeoVintageous/nv/cmds_vi_motions.py", line 1132, in run
    regions_transformer(self.view, move_to_bracket)
  File "/home/code/.config/sublime-text-3/Packages/NeoVintageous/nv/vi/utils.py", line 78, in regions_transformer
    region = f(view, sel)
  File "/home/code/.config/sublime-text-3/Packages/NeoVintageous/nv/cmds_vi_motions.py", line 1117, in move_to_bracket
    a = find_bracket_location(s)
  File "/home/code/.config/sublime-text-3/Packages/NeoVintageous/nv/cmds_vi_motions.py", line 1083, in find_bracket_location
    tag = self.find_tag(pt)
  File "/home/code/.config/sublime-text-3/Packages/NeoVintageous/nv/cmds_vi_motions.py", line 1069, in find_tag
    _, tag = get_closest_tag(self.view, pt)
TypeError: 'NoneType' object is not iterable
```

Related to https://github.com/NeoVintageous/NeoVintageous/issues/180

**Comment by gerardroche** [comment]
Occurs only in HTMl or XML syntaxes.
