### ISSUE TITLE
NeoVintageous 1.10 -- ImportError: cannot import name insert_best_cmdline_completion

### ISSUE THREAD

**Issue by steven-friedman** [NeoVintageous/NeoVintageous#461]
After upgrading to NeoVintageous 1.10, the following traceback prevents NV from running:

reloading plugin NeoVintageous.plugin
Traceback (most recent call last):
  File "/Users/XXX/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/plugin.py", line 65, in <module>
    from NeoVintageous.nv.commands import *  # noqa: F401,F403
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/XXX/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/commands.py", line 35, in <module>
    from NeoVintageous.nv.ex.completions import insert_best_cmdline_completion
ImportError: cannot import name insert_best_cmdline_completion

(Sublime version 3.11, Build 3176)
(MacOS v10.14.3)

**Comment by gerardroche** [comment]
Looks there was a reloading issue when upgrading. This happens sometimes. Sublime should have prompted you with a message to restart Sublime to finish the upgrade. Restarting Sublime will resolve the issue.

**Comment by steven-friedman** [comment]
Tried that before opening this ticket.  Had to pretend that I was on a windows box and shut the box down to clear whatever state had to be cleared.
