### ISSUE TITLE
load_rc bug in 1.19

### ISSUE THREAD

**Issue by dgasmith** [NeoVintageous/NeoVintageous#696]
**Describe the bug**  Since the 1.19 release NeoVintageous does not appear to work ST 3.2.2.

**To Reproduce**  
Install NeoVintageous on Mac with ST 3.2.2.

**Expected behavior**  
The module to load correctly.

**Actual behavior**  
NeoVintageous does not load.

**Versions**  
Show the Sublime Text console log: `Menu > View > Show Console`. 
Example: `3.2.2 build 3211`

**Additional Information**  

```python
ignored packages updated to: ["RestructuredText"]
reloading plugin NeoVintageous.plugin
Traceback (most recent call last):
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/plugin.py", line 61, in <module>
    from NeoVintageous.nv.rc import load_rc
ImportError: cannot import name load_rc
NeoVintageous: update ignored packages with conflicts ['Six', 'Vintage', 'Vintageous']
ignored packages updated to: ["RestructuredText", "Six", "Vintage", "Vintageous"]
unloading plugin Vintage.vintage
unloading plugin Vintage.vintage_commands
unloading plugin Vintage.vintage_motions
generating syntax summary
Traceback (most recent call last):
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/plugin.py", line 173, in plugin_loaded
    load_session()
NameError: global name 'load_session' is not defined
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 196, in load_module
    m.plugin_loaded()
  File "/Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/plugin.py", line 181, in plugin_loaded
    clean_views()
NameError: global name 'clean_views' is not defined
```

**Comment by gerardroche** [comment]
Does the issue persist after restarting Sublime Text? It looks like first-install or update loading issue. The should resolve after a restart and only every happen on some updates.

**Comment by dgasmith** [comment]
Ok, thats very odd. I restarted Sublime after uninstalling/reinstalling previously, but one more restart has everything working?

Regardless, thanks for the fast reply!
