### ISSUE TITLE
Latest version of Sublime Text (4082 and up) has breaking changes

### ISSUE THREAD

**Issue by itsmewes** [NeoVintageous/NeoVintageous#741]
**Describe the bug**  
With the latest version of Sublime Text, Neovintageous does not load.

**To Reproduce**  
1. Update Sublime Text to 4082 or above
2. Restart Sublime Text and a dialog saying "An error occurred trying to load NeoVintageous. Please restart Sublime Text."

**Expected behavior**  
Neovintageous to start up with Sublime without the error.

**Actual behavior**  
A dialog opens saying "An error occurred trying to load NeoVintageous. Please restart Sublime Text."

**Versions**  
startup, version: 4083 osx x64 channel: dev

**Additional Information**  

I know I'm on basically an alpha version of Sublime but thought I would post this here anyway. When I asked about this on the Sublime Text Discord channel one user mentioned:

> It's also an undocumented (hence private?) python module that it uses (Default.history_list), it is to be expected that it may break in the future, which it did now

I'm not sure if this is true, but just adding as much info as I can.

*Update*
Will Bond commented on this on Discord:
>Ah, so NeoVintageous is importing Default/history_list.py, so the Python 3.8 syntax is throwing it off. Hmm, I don't think it will be possible to support it running in two versions, so I'm not sure it is worth trying to fix. Since the history list will be stored in the 3.8 plugin host, trying to use it from within 3.3 will have no effect.
I presume it didn't blow up before, but also didn't actually manipulate the history list successfully in 4xxx builds

Below is the console output:
```
Traceback (most recent call last):
  File "/Users/wesleymartin/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/plugin.py", line 176, in plugin_loaded
    load_rc()
  File "/Users/wesleymartin/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/rc.py", line 51, in load_rc
    _load()
  File "/Users/wesleymartin/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/rc.py", line 70, in _load
    from NeoVintageous.nv.ex_cmds import do_ex_cmdline
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1600, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/wesleymartin/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/ex_cmds.py", line 41, in <module>
    from NeoVintageous.nv.ex.nodes import RangeNode
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1600, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/wesleymartin/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/ex/nodes.py", line 29, in <module>
    from NeoVintageous.nv.marks import get_mark
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1600, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/wesleymartin/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/marks.py", line 20, in <module>
    from NeoVintageous.nv.jumplist import jumplist_back
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1600, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/wesleymartin/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/jumplist.py", line 18, in <module>
    from Default.history_list import get_jump_history
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1600, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Applications/Sublime Text.app/Contents/MacOS/Packages/Default.sublime-package/history_list.py", line 27
    return (f'JumpRecord({self.key!r}, '
                                       ^
SyntaxError: invalid syntax
NeoVintageous: ERROR An error occurred trying to load NeoVintageous. Please restart Sublime Text.
```

**Comment by gerardroche** [comment]
Thanks for reporting it. This seems to also impact LSP (https://github.com/sublimelsp/LSP/pull/1257) and SublimeLinter.

**Comment by godbout** [comment]
@gerardroche, any chance you're gonna set up a GitHub sponsorship? would like to contribute to NeoVintageous monthly, even if it's a small amount. thanks.

**Comment by itsmewes** [comment]
Thank you so much @gerardroche for getting this out so quickly! I really appreciate the hard work you put into this!
