### ISSUE TITLE
visual mode not selecting

### ISSUE THREAD

**Issue by jmlucjav** [NeoVintageous/NeoVintageous#798]
**Describe the bug**  
Visual mode is not working as expected, probably something misconfigured on my side...

**To Reproduce**  
1. I am in normal mode, sublime has 'Line 10, column 6'
2. press shift-v to go to v mode,  sublime has 'V, Line 10, column 6'
3. press arrow down to expand visual selection
4. there is a flicker, the whole line is higlighted for a moment, and the cursor does not move, sublime has 'Line 10, column 6'

**Expected behavior**  
At 4. two lines should be selected in visual mode, and cursor should have moved down 1 line

**Actual behavior**  
Cursor did not move

**Versions**  
Show the Sublime Text console log: `Menu > View > Show Console`. 
startup, version: 4121 windows x64 channel: stable

**Additional Information**  
Also tested with Sublime3, same behaviour

I am sure I am doing something wrong, but after looking through doc/neovintageous.txt I could not find anything that seems related...

thanks

**Comment by gerardroche** [comment]
The flashing line usually means a noop. Does the status bar show a message?

For example when I Visually Select linewise (shift+v) and press `#` it prints:

![Screenshot from 2021-12-09 18-47-22](https://user-images.githubusercontent.com/44148/145457576-96d15ed5-67c3-466b-9a8a-cc32051ea011.png)

Does pressing `j` instead of pressing arrow down work?

**Comment by jmlucjav** [comment]
it just shows 'V, Line 10, column 6'

If I just do a normal selection (v and move cursor) I do see '--VISUAL-- 5 characters selected' but if I do shift-v I get this behaviour...

My neovintageous looks like this:

```
{
	"color_scheme": "Packages/Base16/Themes/base16-cupcake.tmTheme",
	"dark_color_scheme": "Celeste.sublime-color-scheme",
	"font_face": "Agave",
	"font_size": 12,
	"ignored_packages":
	[
		"Six",
		"Vintage",
		"Vintageous",
	],
	"light_color_scheme": "Celeste.sublime-color-scheme",
	"neovintageous_build_version": 11100,
	"vintageous_enable_sneak": true,
	"vintageous_use_sys_clipboard": true,
}
```

thanks!

**Comment by gerardroche** [comment]
I don't know where the `V` in "'V, Line 10, column 6'" is coming from. It should say `VISUAL LINE`. Is it possible to provide some debug information via logging, see https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md

**Comment by jmlucjav** [comment]
Here is the console output:

```
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: V (0x56)
command: nv_feed_key {"key": "V"}
chr evt: j (0x6a)
command: nv_feed_key {"key": "j"}
chr evt: j (0x6a)
command: nv_feed_key {"key": "j"}
command: nv_vi_j {"count": 1, "mode": "mode_normal", "xpos": 185}
command: drag_select {"event": {"button": 1, "x": 671.7, "y": 699.7}}
command: drag_select {"event": {"button": 1, "x": 520.5, "y": 664.5}}
command: drag_select {"event": {"button": 1, "x": 633.3, "y": 435.7}}
command: drag_select {"event": {"button": 1, "x": 725.3, "y": 166.9}}
command: nv_enter_normal_mode {"from_init": true, "mode": "mode_normal"}
command: hide_auto_complete
command: hide_overlay
key evt: ctrl+v
command: nv_feed_key {"key": "<C-v>"}
command: nv_enter_visual_block_mode {"mode": "mode_internal_normal"}
chr evt: j (0x6a)
command: nv_feed_key {"key": "j"}
command: nv_vi_j {"count": 1, "mode": "mode_visual_block", "xpos": 219}
```

In the second line I type V to enter visual line mode. Later I enter block
mode towards the end with ctrl+v.

Here is a similar test with debug output, first I enter char visual mode
with v, and at the end I try to enter visual line mode.

```
DPI mode: per-monitor v2
startup, version: 4121 windows x64 channel: stable
executable: /C/Program Files/Sublime Text/sublime_text.exe
application: /C/Program Files/Sublime Text
working dir: /C/temp
packages path: /C/Users/xx/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/xx/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text/Packages
zip path: /C/Users/xx/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Six", "Vintage", "Vintageous"]
pre session restore time: 0.109422
font face "Agave" could not be found, defaulting to "Consolas"
startup time: 0.183422
first paint time: 0.191422
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading python 3.3 plugin ayu-6.1.2.activation
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line
308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in
_call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in
_call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
reloading plugin Default.fold
  File "<frozen importlib._bootstrap>", line 1512, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in
_call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in
_find_and_load_unlocked
ImportError: No module named 'ayu-6'
reloading python 3.3 plugin ayu-6.1.2.Icons
reloading plugin Default.font
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line
308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
reloading plugin Default.goto_line
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in
_call_with_frames_removed
reloading plugin Default.history_list
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in
_call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in
_find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in
_call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in
_find_and_load_unlocked
ImportError: No module named 'ayu-6'
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin NeoVintageous.plugin
NeoVintageous: DEBUG   [      plugin.py:  44] debug logger initialised
plugins loaded
NeoVintageous: DEBUG   [          rc.py:  50] load
C:\Users\xx\AppData\Roaming\Sublime Text 3\Packages\User\.neovintageousrc
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:vnoremap
<C-S> <C-C>:update<CR><<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>vnoremap
<C-S> <C-C>:update<CR><<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed vnoremap {'content':
'vnoremap', 'name': 'vnoremap', 'target': 'vnoremap', 'params': {'lhs':
'<C-S>', 'rhs': '<C-C>:update<CR>'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: vnoremap
{'lhs': '<C-S>', 'rhs': '<C-C>:update<CR>', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:inoremap
<C-S> <Esc>:update<CR>gi<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>inoremap
<C-S> <Esc>:update<CR>gi<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed inoremap {'content':
'inoremap', 'name': 'inoremap', 'target': 'inoremap', 'params': {'lhs':
'<C-S>', 'rhs': '<Esc>:update<CR>gi'}, 'forced': False, 'addressable':
False, 'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: inoremap
{'lhs': '<C-S>', 'rhs': '<Esc>:update<CR>gi', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:nnoremap
<C-s> :w<CR><<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>nnoremap
<C-s> :w<CR><<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed nnoremap {'content':
'nnoremap', 'name': 'nnoremap', 'target': 'nnoremap', 'params': {'lhs':
'<C-s>', 'rhs': ':w<CR>'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: nnoremap
{'lhs': '<C-s>', 'rhs': ':w<CR>', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:let
mapleader = ','<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>let
mapleader = ','<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed let {'content': 'let',
'name': 'let', 'target': 'let', 'params': {'name': 'mapleader', 'value':
"','"}, 'forced': False, 'addressable': False, 'cooperates_with_global':
False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: let
{'name': 'mapleader', 'value': "','", 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:let
maplocalleader = "\\"<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>let
maplocalleader = "\\"<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed let {'content': 'let',
'name': 'let', 'target': 'let', 'params': {'name': 'maplocalleader',
'value': '"\\\\"'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: let
{'name': 'maplocalleader', 'value': '"\\\\"', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:nnoremap
<leader>bd <Esc>:q<CR><<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>nnoremap
<leader>bd <Esc>:q<CR><<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed nnoremap {'content':
'nnoremap', 'name': 'nnoremap', 'target': 'nnoremap', 'params': {'lhs':
'<leader>bd', 'rhs': '<Esc>:q<CR>'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: nnoremap
{'lhs': '<leader>bd', 'rhs': '<Esc>:q<CR>', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:nnoremap
<leader>d "_d<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>nnoremap
<leader>d "_d<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed nnoremap {'content':
'nnoremap', 'name': 'nnoremap', 'target': 'nnoremap', 'params': {'lhs':
'<leader>d', 'rhs': '"_d'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: nnoremap
{'lhs': '<leader>d', 'rhs': '"_d', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:noremap
<leader>D "_D<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>noremap
<leader>D "_D<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed noremap {'content':
'noremap', 'name': 'noremap', 'target': 'noremap', 'params': {'lhs':
'<leader>D', 'rhs': '"_D'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: noremap
{'lhs': '<leader>D', 'rhs': '"_D', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:noremap
<leader>p "_dP<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>noremap
<leader>p "_dP<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed noremap {'content':
'noremap', 'name': 'noremap', 'target': 'noremap', 'params': {'lhs':
'<leader>p', 'rhs': '"_dP'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: noremap
{'lhs': '<leader>p', 'rhs': '"_dP', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:nnoremap
Vat vatV<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>nnoremap
Vat vatV<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed nnoremap {'content':
'nnoremap', 'name': 'nnoremap', 'target': 'nnoremap', 'params': {'lhs':
'Vat', 'rhs': 'vatV'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: nnoremap
{'lhs': 'Vat', 'rhs': 'vatV', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:nnoremap gV
`[v`]<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>nnoremap gV
`[v`]<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed nnoremap {'content':
'nnoremap', 'name': 'nnoremap', 'target': 'nnoremap', 'params': {'lhs':
'gV', 'rhs': '`[v`]'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: nnoremap
{'lhs': 'gV', 'rhs': '`[v`]', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:noremap Y
y$<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>noremap Y
y$<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed noremap {'content':
'noremap', 'name': 'noremap', 'target': 'noremap', 'params': {'lhs': 'Y',
'rhs': 'y$'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: noremap
{'lhs': 'Y', 'rhs': 'y$', 'view': View(12)}
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:nnoremap
<c-n> :normal n.<cr><<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>nnoremap
<c-n> :normal n.<cr><<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed nnoremap {'content':
'nnoremap', 'name': 'nnoremap', 'target': 'nnoremap', 'params': {'lhs':
'<c-n>', 'rhs': ':normal n.<cr>'}, 'forced': False, 'addressable': False,
'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: nnoremap
{'lhs': '<c-n>', 'rhs': ':normal n.<cr>', 'view': View(12)}
.neovintageousrc file loaded
command: nv_enter_normal_mode {"from_init": true, "mode": "mode_unknown"}
NeoVintageous: DEBUG   [    commands.py:1259] enter NORMAL mode
from=mode_unknown, from_init=True
command: hide_auto_complete
command: hide_overlay
command: nv_enter_normal_mode {"from_init": true, "mode": "mode_normal"}
NeoVintageous: DEBUG   [    commands.py:1259] enter NORMAL mode
from=mode_normal, from_init=True
command: hide_auto_complete
command: hide_overlay
command: drag_select {"event": {"button": 1, "x": 745.3, "y": 393.3}}
chr evt: k (0x6b)
command: nv_feed_key {"key": "k"}
NeoVintageous: INFO    [    commands.py: 515] key evt: k count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveUpByLines>
mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_defs.ViMoveUpByLines'>, <class
'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_k',
'motion_args': {'mode': 'mode_normal', 'count': 1, 'xpos': 634}}
NeoVintageous: INFO    [         vim.py: 134] motion: {'motion': 'nv_vi_k',
'motion_args': {'mode': 'mode_normal', 'count': 1, 'xpos': 634}}
command: nv_vi_k {"count": 1, "mode": "mode_normal", "xpos": 634}
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
chr evt: k (0x6b)
command: nv_feed_key {"key": "k"}
NeoVintageous: INFO    [    commands.py: 515] key evt: k count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveUpByLines>
mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_defs.ViMoveUpByLines'>, <class
'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_k',
'motion_args': {'mode': 'mode_normal', 'count': 1, 'xpos': 634}}
NeoVintageous: INFO    [         vim.py: 134] motion: {'motion': 'nv_vi_k',
'motion_args': {'mode': 'mode_normal', 'count': 1, 'xpos': 634}}
command: nv_vi_k {"count": 1, "mode": "mode_normal", "xpos": 634}
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
command: show_panel {"panel": "console", "toggle": true}
command: drag_select {"event": {"button": 1, "x": 366.1, "y": 67.7}}
command: nv_enter_normal_mode {"from_init": true, "mode": "mode_normal"}
NeoVintageous: DEBUG   [    commands.py:1259] enter NORMAL mode
from=mode_normal, from_init=True
command: hide_auto_complete
command: hide_overlay
chr evt: j (0x6a)
command: nv_feed_key {"key": "j"}
NeoVintageous: INFO    [    commands.py: 515] key evt: j count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveDownByLines>
mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_defs.ViMoveDownByLines'>, <class
'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_j',
'motion_args': {'mode': 'mode_normal', 'count': 1, 'xpos': 324}}
NeoVintageous: INFO    [         vim.py: 134] motion: {'motion': 'nv_vi_j',
'motion_args': {'mode': 'mode_normal', 'count': 1, 'xpos': 324}}
command: nv_vi_j {"count": 1, "mode": "mode_normal", "xpos": 324}
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
chr evt: v (0x76)
command: nv_feed_key {"key": "v"}
NeoVintageous: INFO    [    commands.py: 515] key evt: v count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViEnterVisualMode>
mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_defs.ViEnterVisualMode'>, <class
'NeoVintageous.nv.vi.cmd_base.ViOperatorDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 313] action: {'action':
'nv_enter_visual_mode', 'action_args': {'mode': 'mode_normal'}}
NeoVintageous: INFO    [         vim.py: 139] action: {'action':
'nv_enter_visual_mode', 'action_args': {'mode': 'mode_internal_normal'}}
command: nv_enter_visual_mode {"mode": "mode_internal_normal"}
NeoVintageous: DEBUG   [    commands.py:1440] enter VISUAL mode
from=mode_internal_normal, force=False
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 515] key evt: l count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_visual
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars>
mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class
'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l',
'motion_args': {'mode': 'mode_visual', 'count': 1}}
NeoVintageous: INFO    [         vim.py: 134] motion: {'motion': 'nv_vi_l',
'motion_args': {'mode': 'mode_visual', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_visual"}
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 515] key evt: l count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_visual
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars>
mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class
'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l',
'motion_args': {'mode': 'mode_visual', 'count': 1}}
NeoVintageous: INFO    [         vim.py: 134] motion: {'motion': 'nv_vi_l',
'motion_args': {'mode': 'mode_visual', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_visual"}
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 515] key evt: l count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_visual
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars>
mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class
'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l',
'motion_args': {'mode': 'mode_visual', 'count': 1}}
NeoVintageous: INFO    [         vim.py: 134] motion: {'motion': 'nv_vi_l',
'motion_args': {'mode': 'mode_visual', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_visual"}
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 515] key evt: l count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_visual
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars>
mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class
'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l',
'motion_args': {'mode': 'mode_visual', 'count': 1}}
NeoVintageous: INFO    [         vim.py: 134] motion: {'motion': 'nv_vi_l',
'motion_args': {'mode': 'mode_visual', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_visual"}
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0080 secs
key evt: escape
command: nv_feed_key {"key": "<esc>"}
NeoVintageous: INFO    [    commands.py: 515] key evt: <esc> count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_visual
command: nv_enter_normal_mode {"mode": "mode_visual"}
NeoVintageous: DEBUG   [    commands.py:1259] enter NORMAL mode
from=mode_visual, from_init=False
command: hide_auto_complete
command: hide_overlay
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
chr evt: V (0x56)
command: nv_feed_key {"key": "V"}
NeoVintageous: INFO    [    commands.py: 515] key evt: V count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_normal
NeoVintageous: DEBUG   [    commands.py: 603] found incomplete mapping
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
chr evt: j (0x6a)
command: nv_feed_key {"key": "j"}
NeoVintageous: INFO    [    commands.py: 515] key evt: j count=None
eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved
<ViMissingCommandDef> mode=None sequence=None (<class
'NeoVintageous.nv.vi.cmd_base.ViMissingCommandDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: INFO    [    mappings.py: 192] resolved
<ViMissingCommandDef> mode=None sequence=Vj (<class
'NeoVintageous.nv.vi.cmd_base.ViMissingCommandDef'>, <class
'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0000 secs
command: drag_select {"event": {"button": 1, "x": 685.3, "y": 702.9}}
```

Is this helpful?
thanks

**Comment by gerardroche** [comment]
I think it's because you have some custom mappings that start with `V`. That will block entering visual line mode. It's explained here https://github.com/NeoVintageous/NeoVintageous/issues/308#issuecomment-369446848

**Comment by jmlucjav** [comment]
that was it! thanks!!
