### ISSUE TITLE
Remapped d working incorrectly

### ISSUE THREAD

**Issue by iosemio** [NeoVintageous/NeoVintageous#820]
Greetings all,

As a Dvorak typist I do a few simple remaps in my rc:

```
noremap e d
noremap d h
noremap h gj
noremap t gk
noremap n l
```

With NeoVintageous, remapping 'd' delete to 'e' in this way has issues.

ew and e2w work just fine.
ee deletes 1 line, puts me in insert mode, and gives an error in the console.
e2e details 2 lines, puts me in insert mode, and gives the same error.

Console for ee (e2e matches this console output):

```
NeoVintageous: An error occurred during key press handle:
'Mapping' object has no attribute 'motion_required'
Traceback (most recent call last):
  File "/Users/work/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/commands.py", line 505, in run
    self._feed_key(key, repeat_count, do_eval, check_user_mappings)
  File "/Users/work/Library/Application Support/Sublime Text 3/Installed Packages/NeoVintageous.sublime-package/nv/commands.py", line 697, in _feed_key
    if not command.motion_required:
AttributeError: 'Mapping' object has no attribute 'motion_required'
```

Am I missing something simple?

Many thanks

**Comment by gerardroche** [comment]
Looks like a bug in how some remaps are handled. `e` is a motion an `d` is an operator. It looks like there's a bug when remapping some motions to operators.

**Comment by fzf** [comment]
I am also experiencing this with remapping then triggering what would be dt{some char}. Is there any help we can provide to resolve this?
